import Head from 'next/head';
import React from 'react';
import Footer from './Footer';
import Header from './Header';
// import bg from '../public/images/code.jpg';

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" ">
        <div>
          <Header />
          <main className="h-full">
            <div className="image-bg "></div>
            <div className="max-width ">{children}</div>
          </main>
        </div>
        <Footer />
      </div>
    </>
  );
}
